language: go

go:
  - 1.4

# I know I like my dependencies specified by custom meta tags in HTML!
# Oh wait, no. No I don't.
install: true

script:
  - ./goad init
  - ./goad install
  - ./goad test

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org##polydawn"
    on_success: always
    on_failure: always
    template:
      - |-
        %{repository_slug}: %{result} %{branch}:%{commit} by %{author}. took %{duration}. %{build_url} "%{commit_message}"
    skip_join: true


